### ISSUE TITLE
Clicking "BACKSPACE" in an empty invalid datepicker makes it valid

### ISSUE THREAD

**Issue by blackbaud-joshlandi** [blackbaud/skyux-datetime#94] opened 2019-11-13 21:02 UTC
### Expected behavior
If a datepicker is empty and in an invalid state and I click into it and hit "BAKCSPACE" it should retain it's valid state.

### Actual behavior
Clicking into an invalid datepicker that's empty and invalid (consider the *required* state for the input) and hitting "BACKSPACE" makes it valid.

### Steps to reproduce
Go to: https://developer.blackbaud.com/skyux/components/datepicker#demo

Delete contents of the datepicker under the *Reactive Form Picker* header.

_A date is required_ should show up.

Click "BACKSPACE".

The datepicker is valid.
### Impact
There's risk of incorrect data getting saved.

**Comment by blackbaud-joshlandi** [comment] 2019-11-13 21:02
May be related to #93

**Comment by Blackbaud-AlexKingman** [comment] 2019-11-14 16:43
Thanks @blackbaud-joshlandi . This is indeed a dupe of #93. We're going to close this issue and track its progress there.

**Closed by Blackbaud-AlexKingman** 2019-11-14 16:43 UTC
