### ISSUE TITLE
Date range picker and datepicker components do not support other locales

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux-datetime#38] opened 2019-05-01 15:16 UTC
### Expected behavior

`SkyDateRangePickerComponent` and `SkyDatepickerComponent` should support locales other than `en-US`.

### Actual behavior

They only support `en-US`.

FYI: we recently added Angular 4's `intl` utility to our `SkyDatePipe` source.
https://github.com/blackbaud/skyux-datetime/pull/36

**Comment by Blackbaud-RobertDixon** [comment] 2019-12-11 21:03
Any updates on this issue?  We believe it's the source of a customer bug we have that causes the browser to freeze.

**Comment by Blackbaud-AlexKingman** [comment] 2020-01-28 21:40
This has been solved in a prior PR. Both the date picker and date range picker will support different locales. Also of note: @Blackbaud-RobertDixon 's customer bug (noted above) was caused by using a `moment` date as the model for the date picker. The fix here is to make sure and use `moment`s `.locale()` method to pass the browser's current locale before injecting the date into the datepicker component.

Closing as resolved.

**Closed by Blackbaud-AlexKingman** 2020-01-28 21:40 UTC
Labels: From: Consumer, Impact: High, Severity: High, Type: Bug
