### ISSUE TITLE
Improve date format support for Fuzzy Dates

### ISSUE THREAD

**Issue by Blackbaud-JeffreyAaron** [blackbaud/skyux-datetime#119] opened 2020-02-24 16:18 UTC
### Expected behavior
Date formats should default from the browser's region and all fuzzy date logic (SkyFuzzyDatePipe, SkyFuzzyDateService) should have logic to include/exclude portions of the date format based on which values are defined in the fuzzy date object. (i.e. { month: 1, day: 15 } -> format = 'MM/DD')

### Actual behavior
Consuming logic must figure out the date format and pass that format into the fuzzy date pipe.

### Steps to reproduce
Feed a fuzzy date object into the skyFuzzyDate pipe.

### Severity
Medium???

### Impact
Any code that wants to leverage fuzzy date functionality must determine the format rather than defaulting to the format based on locale.

**Comment by Blackbaud-SteveBrush** [comment] 2020-02-25 16:22
Closing because this is intended behavior. Locale detection should be handled by the consumer to provide the desired formats (since the consumer knows which locales their app supports).

**Comment by Blackbaud-AlexKingman** [comment] 2020-02-27 20:31
Reopening - There is a need to support interfaces in which the user can enter in a fuzzy date with any combination of parts. For example, `02/02/2020` or `02/2020`. Since consumers won't be able to lock this down to one format or the other, the fuzzy date pipe will need to parse out these individual date parts and format them using the locale's short date format.

**Closed** 2020-03-26 14:52 UTC
Labels: From: Consumer, Impact: Medium, Severity: High, Tiger, Type: Enhancement
